name: Build and release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Github Action Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - run: npm ci

      - run: npm run build

      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          # GITHUB_TOKEN is automatically available
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
